### ISSUE TITLE
Heater always on - MOSFET source and drain swapped.

### ISSUE THREAD

**Issue by robets** [henrikssn/TurboCAN#2]
I believe after #76e391446151732316c39055638c21bfe2827c88 the heater MOSFET source and drain got swapped. The symbol is upside down on the schematic, so it matches the fan drivers but drain and source are opposite in the symbol. Had some boards built at #58484556917e8c7f926e563aec05edcaa463c25e and the heater is always active.

Working on a PR to fix it up but wanted to post an issue since it affects the heater. I'm not very fluent with Kicad, so it might take me a little while.

![image](https://user-images.githubusercontent.com/683208/124522030-4fa68980-ddb7-11eb-99b0-9e2c4b077802.png)

**Comment by henrikssn** [comment]
Ouch, thanks for contributing this back! I'll try to take a look at the PR later today.
