### ISSUE TITLE
Is there no klipper config to set usb only?

### ISSUE THREAD

**Issue by johwanghee** [henrikssn/TurboCAN#5]
Is there no klipper config to set usb only?

![1625930186848](https://user-images.githubusercontent.com/25996497/125168256-9218fd80-e1df-11eb-972f-bef4a43e9672.jpg)
USB doesn't work with this

**Comment by henrikssn** [comment]
Hmm, this might need fixing on the Klipper side, USB is connected to the standard PA11/PA12 pins.

You could try using the stm32f042 menu option in the meanwhile, it is close enough to still work IIRC. You should select "USB on PA11/PA12".

**Comment by henrikssn** [comment]
This line should include `MACH_STM32F072`: https://github.com/KevinOConnor/klipper/blob/f24210054a2b263e7a73df1356c77b222851c0a1/src/stm32/Kconfig#L73

**Comment by johwanghee** [comment]
```
config HAVE_STM32_USBFS
    bool
    default y if MACH_STM32F103 || MACH_STM32F042 || MACH_STM32F070 || MACH_STM32F072
```
After fixing the Klipper source, the USB interface is connected.
However, since this is a Klipper issue, I will close this issue.
